import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from '@/app/context/AuthContext';
import ProfileBar from '@/app/components/ProfileBar';
import ShopGlobal from '@/app/components/ShopGlobal';
import WeatherOverlay from '@/app/components/WeatherOverlay';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="vi">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Bọc toàn bộ ứng dụng bên trong AuthProvider */}
        <AuthProvider>
          <ProfileBar />
          <ShopGlobal />
          <WeatherOverlay />
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}

